import{S as h,i}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function d(o){const r="https://pixabay.com/api/",s="44400014-e8ce3fc6f032fabdec0605d2e",n=new URLSearchParams({key:s,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${r}?${n}`;return fetch(e).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const l=document.querySelector(".gallery"),u=document.querySelector(".loader");function g(o){const r=o.map(({webformatURL:s,largeImageURL:n,likes:e,comments:t,downloads:a,views:p,tags:f})=>`<li class="gallery-item">
      <a class="item-link" href="${n}"><img class="item-link" src="${s}" alt="${f}" />
          <div class="thumb">
            <p class="thumb-item">Likes <span class="thumb-counts">${e}</span></p>
            <p class="thumb-item">Views <span class="thumb-counts">${p}</span></p>
            <p class="thumb-item">Comments <span class="thumb-counts">${t}</span></p>
            <p class="thumb-item">Downloads <span class="thumb-counts">${a}</span></p>
          </div></a>
        </li>
  `).join("");l.insertAdjacentHTML("beforeend",r)}function y(){l.innerHTML=""}function b(){u.style.display="inline-block"}function c(){u.style.display="none"}const m=document.querySelector(".search-form"),L=new h(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",S);function S(o){o.preventDefault();const r=m.elements.searchValue.value.trim();if(y(),r===""){i.warning({position:"topRight",title:"Caution",message:"Please enter a search query"});return}b(),setTimeout(()=>{d(r).then(({hits:s})=>{if(c(),s.length===0){i.error({position:"topRight",title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(s),L.refresh()}).catch(s=>{c(),i.error({position:"topRight",title:"Caution",message:"Sorry something wrong! Try again later"}),console.log(s)})},1e3)}
//# sourceMappingURL=commonHelpers.js.map
